services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ebitware
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./4-postgress-queries:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge